In [32]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
url = 'https://www.ssbwiki.com/Top_100_Melee_Players_of_All_Time'

data = requests.get(url)

soup = BeautifulSoup(data.text, 'html.parser')

In [98]:
table = soup.find('table',{'class':'wikitable'})
tbody = table.find('tbody')

In [33]:
df = pd.DataFrame(columns = ['rank','player','empty1','empty2','empty3'])

In [41]:
for row in tbody.find_all('tr'):
    columns = row.find_all('td')
    
    if (columns != []):
        rank = columns[0].text.strip()
        player = columns[1].text.strip()
        empty1 = columns[2].text.strip()
        empty2 = columns[3].text.strip()
        empty3 = columns[4].text.strip()
        
        df = df.append({'rank': rank, 'player': player, 'empty1': empty1, 'empty2': empty2, 'empty3': empty3}, ignore_index = True)

In [42]:
df.head()

  rank     player empty1 empty2 empty3
0    1      Mango      —      —
1    2     Armada      —      —
2    3  Hungrybox      —      —
3    4        Ken      —      —
4    5   Mew2King      —      —

In [80]:
df2 = pd.DataFrame(columns = ['rank','player'])

for row in tbody.find_all('tr'):
    columns = row.find_all('td')
    
    if (columns != []):
        rank = columns[0].text.strip()
        player = columns[1].text.strip()
        
        df2 = df2.append({'rank': rank, 'player': player}, ignore_index = True)

100

In [44]:
df2.head()

  rank     player
0    1      Mango
1    2     Armada
2    3  Hungrybox
3    4        Ken
4    5   Mew2King

In [93]:
df3 = pd.DataFrame(columns = ['main', 'href'])
for tr in tbody.find_all('tr'):
    for td in tbody.find_all('td'):
        character = td.find_all('a')
        
        if (character != []):
            main = character[0]['title']
            href = character[0]['href']
            
            df3 = df3.append({'main':main, 'href': href}, ignore_index = True)

In [96]:
df3

               main                                 href
0               USA  /File:Flag_of_the_United_States.svg
1        Fox (SSBM)                          /Fox_(SSBM)
2            Sweden             /File:Flag_of_Sweden.svg
3      Peach (SSBM)                        /Peach_(SSBM)
4               USA  /File:Flag_of_the_United_States.svg
...             ...                                  ...
20195  Marth (SSBM)                        /Marth_(SSBM)
20196           USA  /File:Flag_of_the_United_States.svg
20197  Marth (SSBM)                        /Marth_(SSBM)
20198           USA  /File:Flag_of_the_United_States.svg
20199    Fox (SSBM)                          /Fox_(SSBM)

[20200 rows x 2 columns]

In [51]:
list1 = []
for link in tbody.find_all('a'):
    list1.append(link.get('title'))

In [89]:
string = 'svga'
if 'svg' not in string:
    print('not in string')
else:
    print('in string!')

in string!

In [111]:
df4 = pd.DataFrame(columns=['secondary'])

for tr in tbody.find_all('tr'):
    for td in tbody.find_all('td'):
        character = td.find_all('a')
        
        if (character != []):
            secondary = character
            
            df4 = df4.append({'secondary' : secondary}, ignore_index = True)

In [112]:
#what is the output of using just character in the if statement?
df4

                                 secondary
0        [[[]], [Mango                  ]]
1                 [[[]], [[]], [[]], [[]]]
2      [[[]], [Armada                   ]]
3                       [[[]], [[]], [[]]]
4      [[[]], [Hungrybox                ]]
...                                    ...
20195                               [[[]]]
20196  [[[]], [Rishi                    ]]
20197                   [[[]], [[]], [[]]]
20198   [[[]], [AbsentPage              ]]
20199                   [[[]], [[]], [[]]]

[20200 rows x 1 columns]

So for having character in the if statement, for each td, I get a list that will contain text. so in this case, each player has a flag and then a separate <a> for their name all in one td. So I get a single entry into the data frame being empty (because the <a> for flag has no text) and their name (since the <a> for name does have text). Then I get the next td entry, which has information on the characters the player plays as. Since Mango has 4 characters, the next element in the dataframe has 4 empty slots (because each <a> for each character does not contain text)

In [113]:
df4 = pd.DataFrame(columns=['secondary'])

for tr in tbody.find_all('tr'):
    for td in tbody.find_all('td'):
        character = td.find_all('a')
        
        if (character != []):
            secondary = character
            
            df4 = df4.append({'secondary' : secondary}, ignore_index = True)

AttributeError: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?